cs2_weapons = {
    "pistols": [
        {"name": "Glock-18",      "price": 0,    "side": "T"},
        {"name": "USP-S",         "price": 0,    "side": "CT"},
        {"name": "P2000",         "price": 0,    "side": "CT"},
        {"name": "Dual Berettas", "price": 300,  "side": "both"},
        {"name": "P250",          "price": 300,  "side": "both"},
        {"name": "Five-SeveN",    "price": 500,  "side": "CT"},
        {"name": "Tec-9",         "price": 500,  "side": "T"},
        {"name": "CZ75-Auto",     "price": 500,  "side": "both"},
        {"name": "Desert Eagle",  "price": 700,  "side": "both"},
        {"name": "R8 Revolver",   "price": 600,  "side": "both"},
    ],
    "mid_tier": [
        {"name": "MAC-10",        "price": 1050, "side": "T"},
        {"name": "MP9",           "price": 1250, "side": "CT"},
        {"name": "MP5-SD",        "price": 1400, "side": "both"},
        {"name": "MP7",           "price": 1400, "side": "both"},
        {"name": "UMP-45",        "price": 1200, "side": "both"},
        {"name": "P90",           "price": 2350, "side": "both"},
        {"name": "PP-Bizon",      "price": 1400, "side": "both"},
        {"name": "Nova",          "price": 1050, "side": "both"},
        {"name": "Sawed-Off",     "price": 1100, "side": "T"},
        {"name": "MAG-7",         "price": 1300, "side": "CT"},
        {"name": "XM1014",        "price": 2000, "side": "both"},
        {"name": "M249",          "price": 5200, "side": "both"},
        {"name": "Negev",         "price": 1700, "side": "both"},
    ],
    "rifles": [
        {"name": "Galil AR",      "price": 1800, "side": "T"},
        {"name": "AK-47",         "price": 2700, "side": "T"},
        {"name": "FAMAS",         "price": 1950, "side": "CT"},
        {"name": "M4A4",          "price": 2900, "side": "CT"},
        {"name": "M4A1-S",        "price": 2900, "side": "CT"},
        {"name": "SG 553",        "price": 3000, "side": "T"},
        {"name": "AUG",           "price": 3300, "side": "CT"},
        {"name": "SSG 08",        "price": 1700, "side": "both"},
        {"name": "AWP",           "price": 4750, "side": "both"},
        {"name": "G3SG1",         "price": 5000, "side": "T"},
        {"name": "SCAR-20",       "price": 5000, "side": "CT"},
    ],
}
cs2_weapons_flat = [w for category in cs2_weapons.values() for w in category]
